# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aritcle',
            options={},
        ),
        migrations.RemoveField(
            model_name='aritcle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='aritcle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aritcle',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='aritcle',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='aritcle',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='aritcle',
            name='tags',
        ),
    ]
