# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20170502_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aritcle',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='aritcle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aritcle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='aritcle',
            name='created_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aritcle',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aritcle',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aritcle',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
    ]
